pivot facet styling, and refactor facet item component and presenter
tulibraries/tul_cob pull request #2160
Opened 2020-09-24 20:32 UTC by quoideneuf

2020-09-24 21:14 UTC, dkinzer requested changes

2020-09-24 21:14 UTC, dkinzer commented on app/helpers/facets_helper.rb
> -    end
The facet values are no longer getting pre_processed ... Should be `BookBot` not `Charlse Library - BookBot`... but I did notice that the selection I do might not be necessary.

![image](https://user-images.githubusercontent.com/444215/94200736-e4737280-fe88-11ea-9692-9f0bfa3ae1e7.png)

2020-09-24 21:14 UTC, dkinzer commented on app/helpers/render_constraints_helper.rb
> +      end
I'm confused as to why this is needed?

2020-09-24 21:15 UTC, dkinzer commented
One other thing I noticed is that at least on my local it's not rendering the way it did in your presentation for locations.  Or it could be that still requires an lc facet to be enabled to render.

2020-09-25 14:04 UTC, quoideneuf commented on app/helpers/facets_helper.rb
> -    end
@dkinzer I moved that into the presenter, take a look and let me know if it looks ok:
https://github.com/tulibraries/tul_cob/pull/2160/commits/1939e2b58d50d42a4eb3cbd51eb79f4a28432363

2020-09-25 14:09 UTC, quoideneuf commented on app/helpers/render_constraints_helper.rb
> +      end
@dkinzer This is preventing behavior where, if you click to cancel the restraint "Bookbot", the restraint for "Charles Library" will take its place. The presenter tacks the "parent" on when it is building the "remove_href" value. Because we are in the constraint pipeline though, we don't have actual objects for "parent" facets like we do when rendering facets.erb. But the struct looks enough like a FacetItem object for the presenter to build the link.

2020-09-25 14:23 UTC, dkinzer commented on app/helpers/render_constraints_helper.rb
> +      end
Maybe we should add a comment about that in the code.  It's not obvious.

2020-09-25 14:28 UTC, quoideneuf commented
> One other thing I noticed is that at least on my local it's not rendering the way it did in your presentation for locations. Or it could be that still requires an lc facet to be enabled to render.

@dkinzer I'm a little stumped by this. Is it possibly a caching issue? The styles should be the same:
https://github.com/tulibraries/tul_cob/pull/2160/files#diff-d2a8cf130312fdf5d4f441c694caa596R4

2020-09-25 14:45 UTC, bibliotechy commented on app/controllers/catalog_controller.rb
> +    config.add_facet_field "lc_facet", label: "LC Call Number", pivot: ["lc_outer_facet", "lc_inner_facet"], limit: true, show: true, component: true, collapsing: true, icons: { show: "", hide: "" },
```suggestion
    config.add_facet_field "lc_facet", label: "Library of Congress Classification", pivot: ["lc_outer_facet", "lc_inner_facet"], limit: true, show: true, component: true, collapsing: true, icons: { show: "", hide: "" }, if: with_call_number_facet?
```

2020-09-25 14:55 UTC, bibliotechy commented
@dkinzer @bh3 I pulled this down locally and both LC and Library facets are rendering as expected, even when LC facets are not present.

2020-09-25 14:56 UTC, dkinzer commented
@bibliotechy It's not rendering for me as expected so I'm not sure what's going on.

2020-09-25 15:40 UTC, bibliotechy commented
@bh3 OK, a quick chat with @dkinzer and I see his point. And actually, I am seeing the extra X even when an LC facet is slected
<img width="488" alt="Screen Shot 2020-09-25 at 11 36 03 AM" src="https://user-images.githubusercontent.com/1128631/94287126-ec342500-ff23-11ea-862e-c2fa5f6404d8.png">

2020-09-25 16:07 UTC, quoideneuf commented
@bibliotechy that doesn't look right. I am afraid that something is wrong with git, but I am not sure how to resolve. I may need to take this branch down and re-post.

2020-09-25 16:35 UTC, quoideneuf commented
@bibliotechy @dkinzer Would you mind pulling down this branch and seeing if it makes a difference? 

https://github.com/tulibraries/tul_cob/tree/BL-1131-facet-styling-squashed

2020-09-25 16:53 UTC, dkinzer commented
@quoideneuf, it's not making a difference for me. Perhaps issue is something local is not yet committed?

2020-09-25 16:56 UTC, bibliotechy commented
@quoideneuf @dkinzer same. No difference.

2020-09-25 17:10 UTC, dkinzer commented on app/presenters/facet_item_presenter.rb
> +      items.each { |i| i.label = i.value.split(" - ", 2).reject { |j| j.blank? }.last }
Why don't we use the helper method that I wrote here where we can less intrusively update at will?  Also I think at least we should add the comments back, because it's not obvious what or why we're doing this.

I don't understand the reject bit as the original code was working without that

2020-09-25 17:12 UTC, dkinzer commented on app/components/facet_item_pivot_component.rb
> +      }
This step might be redundant now that you are basically doing the same thing in `def items` override.

2020-09-25 17:16 UTC, dkinzer commented on spec/helpers/facets_helper_spec.rb
> -    end
We should add these tests back or add the equivalent in the function we update to do the same thing

2020-09-25 17:33 UTC, dkinzer commented on app/presenters/facet_item_presenter.rb
> +      items.each { |i| i.label = i.value.split(" - ", 2).reject { |j| j.blank? }.last }
Is the `.reject { |j| j.blank? }` step necessary?  On qa all location labels are properly rendered without this.

2020-09-25 18:26 UTC, quoideneuf commented on app/presenters/facet_item_presenter.rb
> +      items.each { |i| i.label = i.value.split(" - ", 2).reject { |j| j.blank? }.last }
there was a value in my fixtures that turned up with a blank after the dash. But I can't see it on prod so I'll take the reject out.

2020-09-25 18:40 UTC, quoideneuf commented
@bibliotechy @dkinzer Ok, there was a glitch that I wasn't seeing locally due to my smaller data set. There should only be 1 'X' rendered now when you select an inner facet.

2020-09-25 18:41 UTC, quoideneuf commented on app/presenters/facet_item_presenter.rb
> +      items.each { |i| i.label = i.value.split(" - ", 2).reject { |j| j.blank? }.last }
Took this out - there was a record that had a "Library - " value but in my local collection, but I don't find any on production.

2020-09-25 18:42 UTC, quoideneuf commented on app/components/facet_item_pivot_component.rb
> +      }
👍 Took out the whole thing in fact - it was all redundant.

2020-09-25 18:42 UTC, quoideneuf commented on app/helpers/render_constraints_helper.rb
> +      end
done

2020-09-25 18:43 UTC, quoideneuf commented on app/helpers/facets_helper.rb
> -    end
should be fixed now.

2020-09-25 18:58 UTC, dkinzer approved these changes
This is working nicely for me now.  Assuming tests pass we should move forward with merge.

2020-09-25 19:01 UTC, merged