Fix stimulus-3 deprecation warnings
tulibraries/tul_cob pull request #2976
Opened 2021-11-24 19:47 UTC by dkinzer

Stimulus 3 has added a deprecation warning to data-target attributes because they are going away in future versions of stimulus.

2021-11-29 18:34 UTC, sensei100 commented on app/views/catalog/_explanation_div.html.erb
> +<div class="row bg-background-grey rounded explanation-div mx-1" data-controller="explanation" data-exploration-target="<%= controller_name %>">
```suggestion
<div class="row bg-background-grey rounded explanation-div mx-1" data-controller="explanation" data-explanation-target="<%= controller_name %>">
```

2021-11-29 18:35 UTC, sensei100 commented on app/views/catalog/_index_availability_section.html.erb
> +          <div id="requests-container-<%= document.id %>" class="hidden requests-container float-right" data-controller="requests" data-target="show.request" data-availability-target="request">
@dkinzer I think the show.request target needs to be updated as well.

2021-11-29 18:36 UTC, sensei100 commented on app/views/catalog/_lib_guide_recommender_catalog.html.erb
> +    <div class="d-flex justify-content-between pt-md-1 pb-md-4 px-md-4 catalog-guides" data-libg-guides-target="card">
```suggestion
    <div class="d-flex justify-content-between pt-md-1 pb-md-4 px-md-4 catalog-guides" data-lib-guides-target="card">
```

2021-11-29 18:37 UTC, sensei100 commented on app/views/catalog/_lib_guide_recommender_catalog.html.erb
> -      <div class="lib-guides-recommender-librarians flex-fill p-4 rounded" data-target="lib-guides.flex">
Is there a reason to remove the flex target?

2021-11-29 18:40 UTC, sensei100 requested changes
There are a couple of suggestions, and I think one that was missed.

2021-11-29 21:04 UTC, dkinzer commented on app/views/catalog/_index_availability_section.html.erb
> +          <div id="requests-container-<%= document.id %>" class="hidden requests-container float-right" data-controller="requests" data-target="show.request" data-availability-target="request">
@sensei100 I didn't see this get flagged in the javascript console.  I think we have some targets defined don't actually ever get used.  I wanted to leave them as is to see if we can further clean this up by removing unnecessary data tags.

Can you check to see if that's actually getting used.  I couldn't see where it was getting used.

2021-11-30 16:47 UTC, sensei100 commented on app/views/catalog/_index_availability_section.html.erb
> +          <div id="requests-container-<%= document.id %>" class="hidden requests-container float-right" data-controller="requests" data-target="show.request" data-availability-target="request">
```suggestion
          <div id="requests-container-<%= document.id %>" class="hidden requests-container float-right" data-target="show.request" data-availability-target="request">
```

2021-11-30 16:48 UTC, sensei100 commented on app/views/catalog/_index_availability_section.html.erb
> +          <div id="requests-container-<%= document.id %>" class="hidden requests-container float-right" data-controller="requests" data-target="show.request" data-availability-target="request">
@dkinzer I'm not seeing the deprecation warning either, so I'm okay with leaving it for now to see if we can remove it.  I do notice that we no longer have a requests data-controller, so that should be removed.

2021-12-07 13:28 UTC, sensei100 approved these changes

2021-12-07 13:28 UTC, merged