BL-1621 Google Analytics Tracking
tulibraries/tul_cob pull request #3139
Opened 2022-03-15 17:48 UTC by sensei100

- Updates to classes, ids, and categories to better track click events

2022-03-15 18:56 UTC, ebtoner requested changes
Thanks @sensei100! Here are some things that I noticed reviewing this code
- Is there a reason we need to add the new class "request-btn" when we already have the existing class "request-button"? I'd like to reduce duplication if possible.
- The new "_header" ids for the bento sections look good, but we need to remove the old trackers, I think. For example, we now have a tracker for `bento_books_and_media_header`, so we can remove the tracker for `bento_books_and_media`. Let me know if I'm misunderstanding something here, though. 
- Can we add a tracker for the query list "View More" link as well? 
- See also comments in code

2022-03-15 18:56 UTC, ebtoner commented on app/assets/javascripts/listeners.js
> +      {class: "toggle-bookmark", category: "rrecord-management"},
Update `category: "rrecord-management"` to `category: "record-management"`

2022-03-15 18:56 UTC, ebtoner commented on app/assets/javascripts/listeners.js
> +      {class: "search-results-request-btn", category: "fulfillment"},
This is still using `class: "search-results-request-btn"` which needs to be updated.

2022-03-15 20:10 UTC, sensei100 commented on app/assets/javascripts/listeners.js
> +      {class: "search-results-request-btn", category: "fulfillment"},
I thought we were keeping this class for the actual search-results-request-btn?  I kept that class in the code for the search results, but let me know if I am supposed to take that out.

2022-03-16 20:57 UTC, ebtoner commented on app/assets/javascripts/listeners.js
> +      {class: "search-results-request-btn", category: "fulfillment"},
You're absolutely right. Thanks for clairfying!

2022-03-16 21:08 UTC, ebtoner commented
@sensei100 Everything is looking great! One more detail that I just noticed: In app/helpers/application_helper.rb, I think that the different instances of `link_to "View all #{total} online items", url, class: "bento-full-results"` need to be `link_to "View all #{total} online items", url, class: "bento-online-results"`. What do you think?

2022-03-17 21:34 UTC, ebtoner commented
All the trackers look good! That last change looks like it requires a minor style update, too, though
<img width="490" alt="Screen Shot 2022-03-17 at 5 27 48 PM" src="https://user-images.githubusercontent.com/23346046/158898702-382a50dd-8113-42cc-a39f-6ff292e9db94.png">

2022-03-18 19:40 UTC, ebtoner approved these changes

2022-03-18 19:40 UTC, merged